// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0TgALB7YWIvloyoz37v4fQBb2Vp-iB8g',
    appId: '1:1047982608243:web:4f84cb2ced352bea157f06',
    messagingSenderId: '1047982608243',
    projectId: 'shogly-92332',
    authDomain: 'shogly-92332.firebaseapp.com',
    storageBucket: 'shogly-92332.firebasestorage.app',
    measurementId: 'G-XFKK1MXKK7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHbgT7CEFIceCtw9Ada9aBFkjRrG2bP_A',
    appId: '1:1047982608243:android:be76bebb709fd8d0157f06',
    messagingSenderId: '1047982608243',
    projectId: 'shogly-92332',
    storageBucket: 'shogly-92332.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB0TgALB7YWIvloyoz37v4fQBb2Vp-iB8g',
    appId: '1:1047982608243:web:91999491a780971a157f06',
    messagingSenderId: '1047982608243',
    projectId: 'shogly-92332',
    authDomain: 'shogly-92332.firebaseapp.com',
    storageBucket: 'shogly-92332.firebasestorage.app',
    measurementId: 'G-M4XZ3PQLVL',
  );
}
